### ISSUE TITLE
广播出错

### ISSUE THREAD

**Issue by luoqiz** [SlimeNull/ScreenBroadcaster#7]
os： win11

当我点击广播按钮时提示错误如下图

![image](https://github.com/user-attachments/assets/a18e0284-32b5-4f7f-bcfd-7e52e423bede)

这几个都下载测试过
![image](https://github.com/user-attachments/assets/ce7ecead-7ca4-4fae-a36e-40f7da5ae4c0)

**Comment by SlimeNull** [comment]
不太能看明白是因为什么原因.
